gluster_nodes:
    hosts:
        benki1-nic2.lab.eng.blr.redhat.com:
        benki2-nic2.lab.eng.blr.redhat.com:
    vars:
        gluster_infra_disktype: RAID6
        gluster_infra_diskcount: 12
        gluster_infra_stripe_unit_size: 128
        gluster_infra_volume_groups:
            - vgname: vg_sdb
              pvname: /dev/sdb
            - vgname: vg_sdc
              pvname: /dev/sdc
            - vgname: vg_sdd
              pvname: /dev/sdd
            - vgname: vg_sde
              pvname: /dev/sde
        gluster_infra_thinpools:
            - vgname: vg_sdb
              thinpoolname: thinpool_vg_sdb
              thinpoolsize: 45G
              poolmetadatasize: 1G
            - vgname: vg_sdc
              thinpoolname: thinpool_vg_sdc
              thinpoolsize: 45G
              poolmetadatasize: 1G
            - vgname: vg_sdd
              thinpoolname: thinpool_vg_sdd
              thinpoolsize: 45G
              poolmetadatasize: 1G
            - vgname: vg_sde
              thinpoolname: thinpool_vg_sde
              thinpoolsize: 45G
              poolmetadatasize: 1G
        gluster_infra_lv_logicalvols:
            - vgname: vg_sdb
              thinpool: thinpool_vg_sdb
              lvname: gluster_lv_disk1
              lvsize: 200G
            - vgname: vg_sdc
              thinpool: thinpool_vg_sdc
              lvname: gluster_lv_disk2
              lvsize: 200G
            - vgname: vg_sdd
              thinpool: thinpool_vg_sdd
              lvname: gluster_lv_disk3
              lvsize: 200G
            - vgname: vg_sde
              thinpool: thinpool_vg_sde
              lvname: gluster_lv_disk4
              lvsize: 200G
        gluster_infra_mount_devices:
            - { path: '/dist1', vgname: vg_sdb, lvname: gluster_lv_disk1 }
            - { path: '/dist2', vgname: vg_sdc, lvname: gluster_lv_disk2 }
            - { path: '/dist3', vgname: vg_sdd, lvname: gluster_lv_disk3 }
            - { path: '/dist4', vgname: vg_sde, lvname: gluster_lv_disk4 }
        gluster_infra_fw_ports:
            - 2049/tcp
            - 24007-24050/tcp
            - 49100-49500/tcp
            - 54321/tcp
            - 5900/tcp
            - 5900-6923/tcp
            - 5666/tcp
            - 16514/tcp
        gluster_infra_fw_permanent: true
        gluster_infra_fw_state: enabled
        gluster_infra_fw_zone: public

        # Point to the git repo you want to clone from (and also the version/tag)
        #
        # glusterfs_perf_git_repo: https://review.gluster.org/glusterfs
        # glusterfs_perf_git_version: release-6

        # check which refspec you need to fetch. If you want to test particular
        # patch, you would need to set it up. Remember to uncomment above variable
        # too, if you want to use this. (Visible when you press 'Download'
        # in https://review.gluster.org, particular patch.
        #
        # glusterfs_perf_git_refspec: refs/changes/36/20636/21

        glusterfs_perf_resdir: /var/tmp/glusterperf/{{ansible_date_time.date}}-nightly
        glusterfs_perf_volume: distribute-8-bricks
        glusterfs_perf_bricks: /dist1/1,/dist2/1,/dist3/1,/dist4/1
        glusterfs_perf_hosts: "{{ groups['gluster_nodes'] }}"
        glusterfs_perf_server: "{{ groups['gluster_nodes'][0] }}"
        glusterfs_perf_clients:
            - benki5-nic2.lab.eng.blr.redhat.com
            - benki6-nic2.lab.eng.blr.redhat.com
        glusterfs_perf_client: 'benki5-nic2.lab.eng.blr.redhat.com'
        glusterfs_perf_to_list:
            - sac@redhat.com
            - atumball@redhat.com
